name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: DentinhoJs
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push do SVG
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
